# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  workflow_dispatch:
    inputs:
      ref:
        description: 'Git ref to checkout, can be the branch, tag, or SHA, typically the release Tag'
        required: true

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    
    - uses: actions/checkout@v2
      with:
        repository: thsmi/sieve
        ref: ${{ github.event.inputs.ref }}
    
#    - name: Use Node.js
#      uses: actions/setup-node@v2

    - run: |
        npm install
        npm run gulp web:package
    
    - run : |
        git clone https://github.com/thsmi/sieve-demo.git ./build/demo
        
        mkdir -p ./build/demo/bootstrap
        rm -rf ./build/demo/bootstrap
        cp -r ./build/web/static/libs/bootstrap ./build/demo/bootstrap
        
        mkdir -p ./build/demo/libSieve
        rm -rf ./build/demo/libSieve
        cp -r ./build/web/static/libs/libSieve ./build/demo/libSieve     
        
    - run : |
        cd ./build/demo        
        git status
                        
        git config user.name 'thsmi'
        git config user.email 'thsmi@users.noreply.github.com'
        git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY
        
        git add -A
        git diff-index --quiet HEAD || (git commit -m "Automated update to ${{ github.event.inputs.ref }}" && git push)
        git status        
        
