# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    
    - uses: actions/checkout@v2
      with:
        repository: thsmi/sieve
    
    - name: Use Node.js
      uses: actions/setup-node@v2

    - run: |
        npm install
        npm run gulp web:package
        
    - run : ls ./build/web/static
        
#    - run: npm run build --if-present
#    - run: npm test
